name: Build and Test

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the test project
      run: dotnet build tests/Shonos.FluentCache.Tests/Shonos.FluentCache.Tests.csproj --configuration Release --no-restore

    - name: Run Tests
      run: dotnet test tests/Shonos.FluentCache.Tests/Shonos.FluentCache.Tests.csproj --configuration Release --no-build --verbosity normal

    - name: Build the project
      run: dotnet build Shonos.FluentCache/Shonos.FluentCache.csproj --configuration Release --no-restore

    